<?php

/**
 * Todas las acciones que esten aqui son secciones que estaran restringidas, por lo cual
 * necesitan forzosamente hacer login
 * * */
App::import('Model', 'Group');
$config['App']['permissions'] = array(
    'Index' => array(
        'index' => Group::OPEN
    ),
    'Advanced' => array(
        'index' => Group::MASTER,
        'refresh_salesperson_table' => Group::MASTER,
    ),
    'Ajax' => array(
        'ax_get_home_msg' => Group::CLIENT,
        'ax_process_change_home_msg' => Group::CLIENT,
        'ax_load_all_regions' => Group::CLIENT,        
        'ax_get_company' => Group::CLIENT,
        'ax_get_companies_by_type' => Group::CLIENT,
        'ax_get_clients_distributor' => Group::CLIENT,
        'saveCommentItem' =>  Group::CLIENT,
        'updateCommentItem' =>  Group::CLIENT,
        'refreshCommentsItem' =>  Group::CLIENT,
        'refreshLogConveyor' =>  Group::CLIENT,
        'getRegionsContactByArea' =>  Group::CLIENT,
        'getClientsManager' => Group::MANAGER
    ),
    'Uploader' => array(
        'uploadNicEdit' => Group::MASTER,
        'uploadNicEditReport' => Group::CLIENT,
        'uploadNewsPortada' => Group::MASTER,
        'uploadGenericImg' => Group::CLIENT,
        'createGenericCropImage' => Group::CLIENT,
        'uploadGenericVideo' => Group::CLIENT,
        'uploadGenericFile' => Group::CLIENT
    ),
    'BuoySystems' => array(
        'dashboard' => Group::CLIENT,
        'changeStatus' => Group::CLIENT,  
        'viewBuoyFolder' => Group::CLIENT,
    ),
    'Conveyors' => array(
        'dashboard' => Group::CLIENT,
        'add' => Group::CLIENT,
        'save' => Group::CLIENT,
        'saveUs' => Group::CLIENT,
        'changeStatus' => Group::CLIENT,        
        'update' => Group::CLIENT,
        'processUpdate' => Group::CLIENT,
        'processUpdateUs' => Group::CLIENT,
        'view' => Group::CLIENT,
        'dataSheet' => Group::CLIENT,
        'refreshConveyors' => Group::CLIENT,
        'downloadDatasheet' => Group::CLIENT,
        'downloadDatasheetUs' => Group::CLIENT,
        'conveyorQr' => Group::CLIENT,
        'dropItemToFolder' => Group::CLIENT,
        'revertDroppedItem' => Group::CLIENT,
        'Item' => Group::CLIENT,
        'smartView' => Group::CLIENT,
        'exportSmartview' => Group::CLIENT,
        'reportingHistory' => Group::CLIENT,
        'downloadReportingHistory' => Group::CLIENT,
        'downloadFullReport' => Group::CLIENT,
        //'remove' => Group::CLIENT,
        'remove' => Group::CLIENT,
        'removeItem' => Group::CLIENT,
        'editItem' => Group::CLIENT,
        'trackInfo' => Group::CLIENT,
        'lifeEstimation' => Group::CLIENT,
        'quoteRequest' => Group::CLIENT,
        'refreshItemsConveyor' => Group::CLIENT,
        'refreshItemsFolder' => Group::CLIENT,
        'toggleItemSmartview' => Group::CLIENT,
        'ultrasonic' => Group::CLIENT,
        'ultrasonicData' => Group::CLIENT,
        'saveUltrasonicData' => Group::CLIENT,
        'updateUltrasonicConveyorData' => Group::CLIENT,
        'downloadUltrasonicConveyorData' => Group::CLIENT,
        'addFileConveyor' => Group::CLIENT,
        'saveFileConveyor' => Group::CLIENT,
        'getGaugeChart' => Group::CLIENT,
        'copy' => Group::CLIENT
    ),
    'Tools' => array(
        'tensionOperacionUnitaria' => Group::CLIENT
    ),
    'General' => array(
        'help' => Group::CLIENT,
        'contact' => Group::CLIENT,
        'processContact' => Group::CLIENT
    ),
    'Users' => array(
        'clients' => Group::CLIENT,        
        'add' => Group::CLIENT,
        'save' => Group::CLIENT,
        'companyProfile' => Group::DISTRIBUTOR,
        'updateCompany' => Group::DISTRIBUTOR,        
        'profile' => Group::CLIENT,
        'update' => Group::CLIENT,
        'all' => Group::CLIENT,
        'suspendUnsuspend' => Group::CLIENT,
        'lockUnlock' => Group::MASTER,
        //'delete' => Group::DISTRIBUTOR,
        'delete' => Group::CLIENT,
        'accessData' => Group::CLIENT,
        'updateAccessData' => Group::CLIENT,
        'mobileAdd' => Group::DISTRIBUTOR,
        'securityQuestion' => Group::CLIENT,
        'processSecurityQuestion' => Group::CLIENT,
        'getCompaniesDistributor' => Group::REGION_MANAGER,
        'resendAccountData' => Group::CLIENT,
        'setRegionManager' => Group::CLIENT,
        'clearFingerprint' => Group::MASTER,
        'clearQuestionUser' => Group::MASTER,
    ),
    'Companies' => array(
        'view' => Group::CLIENT,
        'append' => Group::CLIENT,
        'saveCompany' => Group::CLIENT,
        'appendColaborator' => Group::CLIENT,
        'saveColaborator' => Group::CLIENT,
        'reportingHistory' => Group::CLIENT,
        'listReportingConveyors' => Group::CLIENT,
        'suspendUnsuspend' => Group::CLIENT,
        //'delete' => Group::DISTRIBUTOR,
        'delete' => Group::CLIENT,
        'assocClientDistributor' => Group::CLIENT,
        'processAssocClientsDistributor' => Group::CLIENT,
        'clientBucket' => Group::CLIENT,
        'item' => Group::CLIENT,
        'refreshItemsFolder' => Group::CLIENT,
        'removeItem' => Group::CLIENT,
        'processEditItem' => Group::CLIENT,
        'editItem' => Group::CLIENT,
        'saveFileClient' => Group::CLIENT,
        'addFileClient' => Group::CLIENT,
        'saveItemClient' => Group::CLIENT,
        'addItemClient' => Group::CLIENT,
    ),
    'Premium' => array(
        'index' => Group::CLIENT,
        'refreshTrackingConveyors' => Group::CLIENT,
        'changeConveyorStatus' => Group::MASTER,
        'removeConveyor' => Group::MASTER,
        'toggleShowConveyor' => Group::MASTER,
        'addConveyor' => Group::MASTER,
        'saveConveyor' => Group::MASTER,
        'updateConveyor' => Group::MASTER,
        'processUpdateConveyor' => Group::MASTER,
        'monitoringSystem'  => Group::CLIENT,
        'viewMonitoringCompany'  => Group::CLIENT,
        'getColorSensorData'  => Group::CLIENT,
    ),
    'Reports' => array(
        'custom' => Group::CLIENT,
        'addCustomReport' => Group::CLIENT,
        'saveCustomReport' => Group::CLIENT,
        'refreshCustomReports' => Group::CLIENT,
        'updateCustomReport' => Group::CLIENT,
        'processUpdateCustomReport' => Group::CLIENT,
        //'removeCustomReport' => Group::CLIENT,
        'removeCustomReport' => Group::ADMIN,
        'generatePdf' => Group::CLIENT,
        'downloadPdf' => Group::CLIENT
    ),
    'Savings' => array(
        'main' => Group::CLIENT,
        'add' => Group::CLIENT,
        'save' => Group::CLIENT,
        'refreshSavings' => Group::CLIENT,
        'updateCustomReport' => Group::CLIENT,
        'processUpdateCustomReport' => Group::CLIENT,
        //'removeCustomReport' => Group::CLIENT,
        'removeSaving' => Group::ADMIN,
        'generatePdf' => Group::CLIENT,
        'downloadPdf' => Group::CLIENT
    ),
    'History' => array(
        'add' => Group::CLIENT,
        'view' => Group::CLIENT,
        'save' => Group::CLIENT,
        'getConveyorInfo' => Group::CLIENT,
        'downloadData' => Group::CLIENT,
    ),
    'Notifications' => array(
        'add' => Group::DISTRIBUTOR,
        'processAdd' => Group::DISTRIBUTOR,
        'refresh' => Group::CLIENT,
        //'remove' => Group::DISTRIBUTOR,
        'remove' => Group::ADMIN,
        'setByMail' => Group::CLIENT
    )
);
