<div class="title-page terms-section">
    <?php if ($language == IS_ESPANIOL) { ?>
        Pol&iacute;tica de privacidad para M&eacute;xico
    <?php } else { ?>
        Privacy Policy 
    <?php } ?>
    <?php echo __('', true); ?>
</div>
<div class="full-page">
    <div class="data-page">        
        <div class="data-section">
            <div class="terms-data">                
                <?php if ($language == IS_ESPANIOL) { ?>
                    <p>CONTINENTAL bajo responsabilidad de Contitech Mexicana, S.A. de C.V. se compromete a asegurar la privacidad de la informaci&oacute;n personal y profesional obtenida a trav&eacute;s de sus servicios en l&iacute;nea. No obstante, se sugiere leer la normativa descrita a continuaci&oacute;n para entender el tratamiento de los datos proporcionados.</p>
                    <p><b>Protecci&oacute;n de Datos Personales</b><br />
                        Contitech Mexicana, S.A. de C.V. y/o empresas filiales y subsidiarias, con domicilio en la calle Av. Santa Fe 170, piso 7, Colonia Lomas de Santa Fe, en M&eacute;xico, Distrito Federal, es responsable de la confidencialidad, uso y protecci&oacute;n de la informaci&oacute;n personal que el usuario llegar&eacute; a proporcionar a trav&eacute;s del uso del sitio de Internet www.contiplus.net. Por lo anterior su informaci&oacute;n personal ser&aacute; utilizada para fines de contacto y de identificaci&oacute;n en cualquier tipo de relaci&oacute;n jur&iacute;dica que realice con nosotros, as&iacute; como para generar el usuario y contrase&ntilde;a requerido para acceder a los servicios ofrecidos a trav&eacute;s del portal de Internet www.contiplus.net.</p>
                    <p>Para las finalidades anteriores, podr&iacute;amos requerirle su nombre, direcci&oacute;n, tel&eacute;fono, correo electr&oacute;nico y informaci&oacute;n profesional. Para el caso que se desee limitar el uso o divulgaci&oacute;n de su informaci&oacute;n personal, ejercitar sus derechos de acceso, actualizaci&oacute;n, rectificaci&oacute;n, cancelaci&oacute;n o supresi&oacute;n de sus datos personales, as&iacute; como de oposici&oacute;n al tratamiento de los mismos y revocar el consentimiento que para tal fin nos haya otorgado, lo podr&aacute; realizar a trav&eacute;s del siguiente canal de atenci&oacute;n: a trav&eacute;s de nuestro correo electr&oacute;nico www.contiplus.net en cuyo caso se le informar&aacute; los procedimientos a seguir.</p>
                    <p>Cualquier tipo de informaci&oacute;n personal recolectada u obtenida s&oacute;lo ser&aacute; tratada, usada, divulgada o transferida dentro de los l&iacute;mites permitidos por las disposiciones legales de cada jurisdicci&oacute;n en observancia de la presente Pol&iacute;tica de Privacidad o seg&uacute;n como sea definido e informado en cada momento espec&iacute;fico en que se realice la recolecci&oacute;n de datos personales. Le informamos que sus datos personales no ser&aacute;n transferidos a terceros para fines distintos a los aqu&iacute; descritos salvo a aquellos subcontratados por CONTINENTAL para el almacenamiento de los mismos, salvaguardando su protecci&oacute;n y confidencialidad, sin que para ello sea necesario obtener su autorizaci&oacute;n. Usted puede acceder a la lista de los receptores de la informaci&oacute;n visitando [incluir link].</p>
                    <p>Para verificar los candados de seguridad SSL, cookies y otras herramientas de rastreo favor de visitar &ldquo;seguridad del sitio&rdquo;. Para verificar los cambios al presente aviso, lo podr&aacute; realizar en la p&aacute;gina www.contiplus.net</p>
                    <p><b>Tipo de informaci&oacute;n</b><br />
                        Se recopilar&aacute; la informaci&oacute;n de diferentes formas y desde distintas &aacute;reas del sitio web www.contiplus.net</p>
                    <p>Se sujetar&aacute;n a las normas de seguridad y privacidad todos aquellos datos personales cuya recolecci&oacute;n hayan sido autorizados por el usuario de forma previa y voluntariamente en dicha direcci&oacute;n electr&oacute;nica.</p>
                    <p>Se solicitar&aacute; informaci&oacute;n como:<br />
                        -&nbsp;&nbsp; &nbsp;Nombre (s) y apellidos.<br />
                        -&nbsp;&nbsp; &nbsp;Correo electr&oacute;nico.<br />
                        -&nbsp;&nbsp; &nbsp;Tel&eacute;fono.<br />
                        -&nbsp;&nbsp; &nbsp;Datos profesionales.</p>
                    <p>La informaci&oacute;n solicitada permitir&aacute; contactar a los usuarios cuando sea necesario. Los usuarios podr&aacute;n ser contactados por tel&eacute;fono o correo electr&oacute;nico en caso de que se requieran datos adicionales para completar alguna solicitud, en cuyo caso, de tratarse de datos personales, ser&aacute; requerida una autorizaci&oacute;n adicional.</p>
                    <p><b>Retenci&oacute;n, supresi&oacute;n y destrucci&oacute;n de la informaci&oacute;n</b></p>
                    <p>CONTINENTAL s&oacute;lo retendr&aacute; sus datos personales hasta que el prop&oacute;sito para el que fueron recolectados sea cumplido y una vez finalizado dicho prop&oacute;sito, hasta el t&eacute;rmino requerido y permitido por la ley con el fin de dar aplicaci&oacute;n a las disposiciones aplicables de retenci&oacute;n de informaci&oacute;n.</p>
                    <p>Cuando el prop&oacute;sito para el cual la informaci&oacute;n fue recolectada haya cesado, dicha informaci&oacute;n ser&aacute; separada a una base de datos distinta y almacenada por cierto periodo de tiempo por razones de protecci&oacute;n de informaci&oacute;n de acuerdo a las pol&iacute;ticas internas de CONTINENTAL y otras leyes y disposiciones aplicables.</p>
                    <p>Para la destrucci&oacute;n de la informaci&oacute;n personal suministrada por los usuarios, CONTINENTAL tomar&aacute; todas las medidas necesarias para garantizar que la reproducci&oacute;n o recuperaci&oacute;n f&iacute;sica o digital de la misma no sea posible.</p>
                    <p><b>Uso adicionales</b><br />
                        La informaci&oacute;n suministrada durante el proceso de registro, inscripci&oacute;n a alg&uacute;n programa y promociones, se emplea de forma agregada para realizar estudios internos sobre los datos demogr&aacute;ficos, intereses y comportamiento de los usuarios; con la finalidad de proporcionarles productos, servicios y contenidos acordes a sus necesidades.</p>
                    <p><b>Protecci&oacute;n</b><br />
                        A pesar de contar cada d&iacute;a con herramientas m&aacute;s seguras, la protecci&oacute;n de los datos enviados a trav&eacute;s de Internet no se puede garantizar al 100%; por lo que una vez recibidos, se har&aacute; todo lo posible por salvaguardar la informaci&oacute;n.</p>
                    <p>El usuario es responsable de mantener la confidencialidad del usuario y contrase&ntilde;a para el ingreso al portal electr&oacute;nico www.contiplus.net. El usuario es responsable de los usos relacionados con su usuario y contrase&ntilde;a a trav&eacute;s del portal electr&oacute;nico www.contiplus.net, incluso en los casos en que dichos usos no hayan sido por &eacute;l autorizados.&nbsp;</p>
                    <p><b>Cookies</b><br />
                        Las cookies son peque&ntilde;as piezas de informaci&oacute;n que son enviadas por el sitio web al navegador.</p>
                    <p>Se almacenan en el disco duro de los equipos y utilizan para determinar las preferencias de los usuarios que acceden al portal electr&oacute;nico (www.contiplus.net), as&iacute; como para rastrear determinados comportamientos o actividades.</p>
                    <p>Las cookies permiten reconocer a los usuarios, detectar el ancho de banda que han seleccionado, identificar la informaci&oacute;n m&aacute;s destacada, calcular el tama&ntilde;o de la audiencia y medir algunos par&aacute;metros de tr&aacute;fico.</p>
                    <p><b>Confidencialidad</b><br />
                        Cuando el usuario se encuentre en el sitio web (www.contiplus.net), compartir&aacute; su informaci&oacute;n, salvo que se especifique lo contrario.</p>
                    <p>CONTINENTAL, no tiene obligaci&oacute;n alguna de mantener confidencial cualquier otra informaci&oacute;n que el usuario proporcione por medio de boletines y pl&aacute;ticas en l&iacute;nea (chats), as&iacute; como a trav&eacute;s de las cookies.</p>
                    <p>S&oacute;lo se podr&aacute; difundir la informaci&oacute;n en casos especiales, como identificar, localizar o realizar acciones legales contra aquellas personas que infrinjan las condiciones de servicio del sitio web (www.contiplus.net), causen da&ntilde;os a, o interfieran en, los derechos de CONTINENTAL, sus propiedades, de otros usuarios del portal o de cualquier persona que pudiese resultar perjudicada por dichas acciones.</p>
                    <p>CONTINENTAL NO vender&aacute;, regalar&aacute;, facilitar&aacute; ni alquilar&aacute; informaci&oacute;n confidencial a terceros. Si el usuario no desea que sus datos sean compartidos, podr&aacute; prescindir de un servicio determinado o abstenerse de participar en algunas actividades.</p>
                    <p>CONTINENTAL NO compartir&aacute; informaci&oacute;n confidencial con terceras partes, salvo expresa autorizaci&oacute;n de sus suscriptores o cuando por medio de una orden judicial se requiera para cumplir con ciertas disposiciones procesales.</p>
                    <p><b>Modificaciones en las Pol&iacute;ticas de Privacidad</b><br />
                        CONTINENTAL se reserva el derecho de efectuar en cualquier momento, modificaciones en las presentes pol&iacute;ticas de privacidad y adaptarlas a novedades legislativas, jurisprudenciales, as&iacute; como a pr&aacute;cticas del mercado. Las modificaciones sustanciales de la Pol&iacute;tica de Privacidad ser&aacute;n comunicadas al Titular antes o a m&aacute;s tardar al momento de implementar la modificaci&oacute;n. Cuando la modificaci&oacute;n verse sobre la finalidad del tratamiento de la informaci&oacute;n, CONTINENTAL solicitar&aacute; una nueva autorizaci&oacute;n al Titular de la informaci&oacute;n. .<br />
                        <b>Vigencia</b><br />
                        La presente Pol&iacute;tica de Privacidad se encuentra vigente desde el 01 de Enero de 2014.</p>                
                <?php } else { ?>
                    <p>CONTINENTAL under the responsibility of Contitech Mexicana, SA de C.V. is committed to ensuring the privacy of personal and professional information obtained through its services online. However, it is suggested to read the rules described below to understand the processing of the data provided.</p><p>Personal Data Protection<br />
                        Contitech Mexicana, SA de C.V. and / or subsidiaries and affiliates, residing at Av. Santa Fe 170, 7th floor, Colonia Lomas de Santa Fe in Mexico, Federal District, is responsible for the confidentiality, use and protection of personal information the user I get to provide through use of the website www.contiplus.net. Therefore your personal information will be used for contact purposes and identification in any type of legal relationship you have with us as well as to generate the required username and password to access the services offered through the Internet portal www.contiplus .net.</p><p>For the above purposes, we may require your name, address, telephone, email and professional information. In case you wish to limit the use or disclosure of your personal information, exercise your right to access, update, modify, cancel or delete your personal data as well as to oppose the processing thereof and revoke the consent for that so you have given us, what can be done through the following service channel: through our email admin@contiplus.net in which case they will inform the procedures.</p><p><br />
                        Any personal information collected or obtained only be treated, used, disclosed or transferred within the limits allowed by the laws of each jurisdiction in compliance with this Privacy Policy or as as defined and informed at all times specific in that collection of personal data is performed. Please note that your personal data will not be transferred to third parties for purposes other than those described herein except those subcontracted by CONTINENTAL for storing them, ensuring their protection and confidentiality, without being necessary to obtain approval. You can access the list of recipients of the information visiting www.contitech.com.mx, www.arlosrestrepos.com y www.humann.tech</p><p>To verify SSL security locks, cookies and other tracking tools please visit &quot;site security&quot; in your browser.</p><p>Type of information<br />
                        Information will be collected in different ways and from different areas of the website www.contiplus.ne<br />
                        Shall be subject to the safety and privacy all personal data whose collection authorized by the user prior to and voluntarily in that email address.<br />
                        Information will be required as:<br />
                        - Name (s) and surname.<br />
                        - Email.<br />
                        - Telephone.<br />
                        - Professional Data.</p>
                    <p>Contact information requested allow users when necessary. Users can be contacted by phone or email if additional information is required to complete any application, in which case, in case of personal data, will be required an additional authorization.</p><p>Retention, suppression and destruction of information</p><p>CONTINENTAL retain your personal data only until the purpose for which they were collected is fulfilled that purpose and once completed, to the term required and permitted by law to give effect to the applicable provisions of withholding information.</p><p>When the purpose for which the information was collected ceases, such information shall be spaced a different database and stored for a period of time for reasons of protection of information according to internal policies CONTINENTAL and other laws and regulations applicable .</p><p>For the destruction of personal information provided by users, CONTINENTAL take all necessary measures to ensure that the physical or digital reproduction or recovery from it is not possible measures.</p><p>Additional use<br />
                        The information provided during the registration process, a program enrollment and promotions, is used in aggregate form for internal research on the demographics, interests and behavior of users; in order to provide products, services and content tailored to their needs.</p><p>Protection<br />
                        Despite having every day with safer tools, protection of data sent over the Internet can not be guaranteed to be 100%; so that once received, will make every effort to safeguard the information.</p><p>You are responsible for maintaining the confidentiality of the username and password for entering the electronic portal www.contiplus.net. The user is responsible for related uses your username and password via electronic portal www.contiplus.net, even in cases where such uses have not been authorized by him.</p><p>Cookies<br />
                        Cookies are small pieces of information that are sent by the website to the browser.<br />
                        Are stored on the hard disk of the equipment and used to determine the preferences of users accessing the electronic portal (www.contiplus.net) as well as to track certain behaviors or activities.</p><p>Cookies can recognize users, detect the bandwidth they have selected, identify salient information, calculate the size of the audience and measure certain traffic parameters.</p><p><br />
                        Notice<br />
                        When the user is on the website (www.contiplus.net), share their information, unless otherwise specified.</p><p>CONTINENTAL not have any obligation to keep confidential any information you provide through newsletters and online discussions (chats) and through cookies.</p><p>Only be spread information in special cases, such as identifying, locating or bring legal action against those who violate the terms of use of the website (www.contiplus.net), causing damage to, or interfere with the rights of CONTINENTAL, property, other users of the portal or anyone who could be harmed by such activities.</p><p>CONTINENTAL NOT sell, give away, or rent provide confidential information to third parties. If the user does not want your data to be shared, you can do without a certain service or refrain from engaging in certain activities.</p><p>CONTINENTAL NOT share confidential information with third parties, unless authorized by your subscribers or when through a court order is required to comply with certain procedural requirements.</p><p>Modifications to Privacy Policy<br />
                        CONTINENTAL reserves the right to make at any time changes to the privacy policies and adapt to new legislation, case law, as well as market practices. Substantial changes to the Privacy Policy will be communicated to the Contractor before or at the latest when implementing the change. When the change seen on the purpose of processing information, CONTINENTAL request a new authorization holder information. .<br />
                        validity</p>
                <?php } ?>
            </div>
        </div>
    </div>
</div>
<?php if ($language == IS_ESPANIOL) { ?>
    <div class="title-page terms-section">
        P&oacute;litica de privacidad para Colombia
    </div>   
    <div class="full-page">
        <div class="data-page">        
            <div class="data-section">
                <div class="terms-data">
                    <p>CONTINENTAL bajo responsabilidad de Contitech Mexicana, S.A. de C.V. se compromete a asegurar la privacidad de la informaci&oacute;n personal y profesional obtenida a trav&eacute;s de sus servicios en l&iacute;nea. No obstante, se sugiere leer la normativa descrita a continuaci&oacute;n para entender el tratamiento de los datos proporcionados.</p>
                    <p><b>Protecci&oacute;n de Datos Personales</b><br />
                        Contitech Mexicana, S.A. de C.V. y/o empresas filiales y subsidiarias, con domicilio en la calle Av. Santa Fe 170, piso 7, Colonia Lomas de Santa Fe, en M&eacute;xico, Distrito Federal, es responsable de la confidencialidad, uso y protecci&oacute;n de la informaci&oacute;n personal que el usuario llegar&eacute; a proporcionar a trav&eacute;s del uso del sitio de Internet www.contiplus.net. Por lo anterior su informaci&oacute;n personal ser&aacute; utilizada para fines de contacto y de identificaci&oacute;n en cualquier tipo de relaci&oacute;n jur&iacute;dica que realice con nosotros, as&iacute; como para generar el usuario y contrase&ntilde;a requerido para acceder a los servicios ofrecidos a trav&eacute;s del portal de Internet www.contiplus.net.</p>
                    <p>Para las finalidades anteriores, podr&iacute;amos requerirle su nombre, direcci&oacute;n, tel&eacute;fono, correo electr&oacute;nico y informaci&oacute;n profesional. Para el caso que se desee limitar el uso o divulgaci&oacute;n de su informaci&oacute;n personal, ejercitar sus derechos de acceso, actualizaci&oacute;n, rectificaci&oacute;n, cancelaci&oacute;n o supresi&oacute;n de sus datos personales, as&iacute; como de oposici&oacute;n al tratamiento de los mismos y revocar el consentimiento que para tal fin nos haya otorgado, lo podr&aacute; realizar a trav&eacute;s del siguiente canal de atenci&oacute;n: a trav&eacute;s de nuestro correo electr&oacute;nico <b>www.contiplus.net</b> en cuyo caso se le informar&aacute; los procedimientos a seguir.</p>
                    <p>Cualquier tipo de informaci&oacute;n personal recolectada u obtenida s&oacute;lo ser&aacute; tratada, usada, divulgada o transferida dentro de los l&iacute;mites permitidos por las disposiciones legales de cada jurisdicci&oacute;n en observancia de la presente Pol&iacute;tica de Privacidad o seg&uacute;n como sea definido e informado en cada momento espec&iacute;fico en que se realice la recolecci&oacute;n de datos personales. Le informamos que sus datos personales no ser&aacute;n transferidos a terceros para fines distintos a los aqu&iacute; descritos salvo a aquellos subcontratados por CONTINENTAL para el almacenamiento de los mismos, salvaguardando su protecci&oacute;n y confidencialidad, sin que para ello sea necesario obtener su autorizaci&oacute;n. Usted puede acceder a la lista de los receptores de la informaci&oacute;n visitando [incluir link].</p>
                    <p>Para verificar los candados de seguridad SSL, cookies y otras herramientas de rastreo favor de visitar &ldquo;seguridad del sitio&rdquo;. Para verificar los cambios al presente aviso, lo podr&aacute; realizar en la p&aacute;gina www.contiplus.net</p>
                    <p><b>Tipo de informaci&oacute;n</b><br />
                        Se recopilar&aacute; la informaci&oacute;n de diferentes formas y desde distintas &aacute;reas del sitio web www.contiplus.net</p>
                    <p>Se sujetar&aacute;n a las normas de seguridad y privacidad todos aquellos datos personales cuya recolecci&oacute;n hayan sido autorizados por el usuario de forma previa y voluntariamente en dicha direcci&oacute;n electr&oacute;nica.</p>
                    <p>Se solicitar&aacute; informaci&oacute;n como:<br />
                        -&nbsp;&nbsp; &nbsp;Nombre (s) y apellidos.<br />
                        -&nbsp;&nbsp; &nbsp;Correo electr&oacute;nico.<br />
                        -&nbsp;&nbsp; &nbsp;Tel&eacute;fono.<br />
                        -&nbsp;&nbsp; &nbsp;Datos profesionales.</p>
                    <p>La informaci&oacute;n solicitada permitir&aacute; contactar a los usuarios cuando sea necesario. Los usuarios podr&aacute;n ser contactados por tel&eacute;fono o correo electr&oacute;nico en caso de que se requieran datos adicionales para completar alguna solicitud, en cuyo caso, de tratarse de datos personales, ser&aacute; requerida una autorizaci&oacute;n adicional.</p>
                    <p><b>Retenci&oacute;n, supresi&oacute;n y destrucci&oacute;n de la informaci&oacute;n</b></p>
                    <p>CONTINENTAL s&oacute;lo retendr&aacute; sus datos personales hasta que el prop&oacute;sito para el que fueron recolectados sea cumplido y una vez finalizado dicho prop&oacute;sito, hasta el t&eacute;rmino requerido y permitido por la ley con el fin de dar aplicaci&oacute;n a las disposiciones aplicables de retenci&oacute;n de informaci&oacute;n.</p>
                    <p>Cuando el prop&oacute;sito para el cual la informaci&oacute;n fue recolectada haya cesado, dicha informaci&oacute;n ser&aacute; separada a una base de datos distinta y almacenada por cierto periodo de tiempo por razones de protecci&oacute;n de informaci&oacute;n de acuerdo a las pol&iacute;ticas internas de CONTINENTAL y otras leyes y disposiciones aplicables.</p>
                    <p>Para la destrucci&oacute;n de la informaci&oacute;n personal suministrada por los usuarios, CONTINENTAL tomar&aacute; todas las medidas necesarias para garantizar que la reproducci&oacute;n o recuperaci&oacute;n f&iacute;sica o digital de la misma no sea posible.</p>
                    <p><b>Uso adicionales</b><br />
                        La informaci&oacute;n suministrada durante el proceso de registro, inscripci&oacute;n a alg&uacute;n programa y promociones, se emplea de forma agregada para realizar estudios internos sobre los datos demogr&aacute;ficos, intereses y comportamiento de los usuarios; con la finalidad de proporcionarles productos, servicios y contenidos acordes a sus necesidades.</p>
                    <p><b>Protecci&oacute;n</b><br />
                        A pesar de contar cada d&iacute;a con herramientas m&aacute;s seguras, la protecci&oacute;n de los datos enviados a trav&eacute;s de Internet no se puede garantizar al 100%; por lo que una vez recibidos, se har&aacute; todo lo posible por salvaguardar la informaci&oacute;n.</p>
                    <p>El usuario es responsable de mantener la confidencialidad del usuario y contrase&ntilde;a para el ingreso al portal electr&oacute;nico www.contiplus.net. El usuario es responsable de los usos relacionados con su usuario y contrase&ntilde;a a trav&eacute;s del portal electr&oacute;nico www.contiplus.net, incluso en los casos en que dichos usos no hayan sido por &eacute;l autorizados.&nbsp;</p>
                    <p><b>Cookies</b><br />
                        Las cookies son peque&ntilde;as piezas de informaci&oacute;n que son enviadas por el sitio web al navegador.</p>
                    <p>Se almacenan en el disco duro de los equipos y utilizan para determinar las preferencias de los usuarios que acceden al portal electr&oacute;nico (www.contiplus.net), as&iacute; como para rastrear determinados comportamientos o actividades.</p>
                    <p>Las cookies permiten reconocer a los usuarios, detectar el ancho de banda que han seleccionado, identificar la informaci&oacute;n m&aacute;s destacada, calcular el tama&ntilde;o de la audiencia y medir algunos par&aacute;metros de tr&aacute;fico.</p>
                    <p><b>Confidencialidad</b><br />
                        Cuando el usuario se encuentre en el sitio web (www.contiplus.net), compartir&aacute; su informaci&oacute;n, salvo que se especifique lo contrario.</p>
                    <p>CONTINENTAL, no tiene obligaci&oacute;n alguna de mantener confidencial cualquier otra informaci&oacute;n que el usuario proporcione por medio de boletines y pl&aacute;ticas en l&iacute;nea (chats), as&iacute; como a trav&eacute;s de las cookies.</p>
                    <p>S&oacute;lo se podr&aacute; difundir la informaci&oacute;n en casos especiales, como identificar, localizar o realizar acciones legales contra aquellas personas que infrinjan las condiciones de servicio del sitio web (www.contiplus.net), causen da&ntilde;os a, o interfieran en, los derechos de CONTINENTAL, sus propiedades, de otros usuarios del portal o de cualquier persona que pudiese resultar perjudicada por dichas acciones.</p>
                    <p>CONTINENTAL NO vender&aacute;, regalar&aacute;, facilitar&aacute; ni alquilar&aacute; informaci&oacute;n confidencial a terceros. Si el usuario no desea que sus datos sean compartidos, podr&aacute; prescindir de un servicio determinado o abstenerse de participar en algunas actividades.</p>
                    <p>CONTINENTAL NO compartir&aacute; informaci&oacute;n confidencial con terceras partes, salvo expresa autorizaci&oacute;n de sus suscriptores o cuando por medio de una orden judicial se requiera para cumplir con ciertas disposiciones procesales.</p>
                    <p><b>Modificaciones en las Pol&iacute;ticas de Privacidad</b><br />
                        CONTINENTAL se reserva el derecho de efectuar en cualquier momento, modificaciones en las presentes pol&iacute;ticas de privacidad y adaptarlas a novedades legislativas, jurisprudenciales, as&iacute; como a pr&aacute;cticas del mercado. Las modificaciones sustanciales de la Pol&iacute;tica de Privacidad ser&aacute;n comunicadas al Titular antes o a m&aacute;s tardar al momento de implementar la modificaci&oacute;n. Cuando la modificaci&oacute;n verse sobre la finalidad del tratamiento de la informaci&oacute;n, CONTINENTAL solicitar&aacute; una nueva autorizaci&oacute;n al Titular de la informaci&oacute;n. .<br />
                        <b>Vigencia</b><br />
                        La presente Pol&iacute;tica de Privacidad se encuentra vigente desde el [incluir fecha].</p>
                </div>
            </div>
        </div>
    </div>
    <div class="title-page terms-section">
        P&oacute;litica de privacidad para Argentina
    </div>   
    <div class="full-page">
        <div class="data-page">        
            <div class="data-section">
                <div class="terms-data">
                    <p>CONTINENTAL bajo responsabilidad de Contitech Mexicana, S.A. de C.V. se compromete a asegurar la privacidad de la informaci&oacute;n personal y profesional obtenida a trav&eacute;s de sus servicios en l&iacute;nea. No obstante, se sugiere leer la normativa descrita a continuaci&oacute;n para entender el tratamiento de los datos proporcionados.</p>
                    <p><b>Protecci&oacute;n de Datos Personales</b><br />
                        Contitech Mexicana, S.A. de C.V. y/o empresas filiales y subsidiarias, con domicilio en la calle Av. Santa Fe 170, piso 7, Colonia Lomas de Santa Fe, en M&eacute;xico, Distrito Federal, es responsable de la confidencialidad, uso y protecci&oacute;n de la informaci&oacute;n personal que el usuario llegar&eacute; a proporcionar a trav&eacute;s del uso del sitio de Internet www.contiplus.net. Por lo anterior su informaci&oacute;n personal ser&aacute; utilizada para fines de contacto y de identificaci&oacute;n en cualquier tipo de relaci&oacute;n jur&iacute;dica que realice con nosotros, as&iacute; como para generar el usuario y contrase&ntilde;a requerido para acceder a los servicios ofrecidos a trav&eacute;s del portal de Internet www.contiplus.net.</p>
                    <p>Para las finalidades anteriores, podr&iacute;amos requerirle su nombre, direcci&oacute;n, tel&eacute;fono, correo electr&oacute;nico y informaci&oacute;n profesional. Para el caso que se desee limitar el uso o divulgaci&oacute;n de su informaci&oacute;n personal, ejercitar sus derechos de acceso, actualizaci&oacute;n, rectificaci&oacute;n, cancelaci&oacute;n o supresi&oacute;n de sus datos personales, as&iacute; como de oposici&oacute;n al tratamiento de los mismos y revocar el consentimiento que para tal fin nos haya otorgado, lo podr&aacute; realizar a trav&eacute;s del siguiente canal de atenci&oacute;n: a trav&eacute;s de nuestro correo electr&oacute;nico:admin@contiplus.net,,en cuyo caso se le informar&aacute; los procedimientos a seguir.</p>
                    <p>Cualquier tipo de informaci&oacute;n personal recolectada u obtenida s&oacute;lo ser&aacute; tratada, usada, divulgada o transferida dentro de los l&iacute;mites permitidos por las disposiciones legales de cada jurisdicci&oacute;n en observancia de la presente Pol&iacute;tica de Privacidad o seg&uacute;n como sea definido e informado en cada momento espec&iacute;fico en que se realice la recolecci&oacute;n de datos personales. Le informamos que sus datos personales no ser&aacute;n transferidos a terceros para fines distintos a los aqu&iacute; descritos salvo a aquellos subcontratados por CONTINENTAL para el almacenamiento de los mismos, salvaguardando su protecci&oacute;n y confidencialidad, sin que para ello sea necesario obtener su autorizaci&oacute;n. Usted puede acceder a la lista de los receptores de la informaci&oacute;n visitando [incluir link].</p>
                    <p>Para verificar los candados de seguridad SSL, cookies y otras herramientas de rastreo favor de visitar &ldquo;seguridad del sitio&rdquo;. Para verificar los cambios al presente aviso, lo podr&aacute; realizar en la p&aacute;gina www.contiplus.net</p>
                    <p><b>Tipo de informaci&oacute;n</b><br />
                        Se recopilar&aacute; la informaci&oacute;n de diferentes formas y desde distintas &aacute;reas del sitio web www.contiplus.net</p>
                    <p>Se sujetar&aacute;n a las normas de seguridad y privacidad todos aquellos datos personales cuya recolecci&oacute;n hayan sido autorizados por el usuario de forma previa y voluntariamente en dicha direcci&oacute;n electr&oacute;nica.</p>
                    <p>Se solicitar&aacute; informaci&oacute;n como:<br />
                        -&nbsp;&nbsp; &nbsp;Nombre (s) y apellidos.<br />
                        -&nbsp;&nbsp; &nbsp;Correo electr&oacute;nico.<br />
                        -&nbsp;&nbsp; &nbsp;Tel&eacute;fono.<br />
                        -&nbsp;&nbsp; &nbsp;Datos profesionales.</p>
                    <p>La informaci&oacute;n solicitada permitir&aacute; contactar a los usuarios cuando sea necesario. Los usuarios podr&aacute;n ser contactados por tel&eacute;fono o correo electr&oacute;nico en caso de que se requieran datos adicionales para completar alguna solicitud, en cuyo caso, de tratarse de datos personales, ser&aacute; requerida una autorizaci&oacute;n adicional.</p>
                    <p><b>Retenci&oacute;n, supresi&oacute;n y destrucci&oacute;n de la informaci&oacute;n</b></p>
                    <p>CONTINENTAL s&oacute;lo retendr&aacute; sus datos personales hasta que el prop&oacute;sito para el que fueron recolectados sea cumplido y una vez finalizado dicho prop&oacute;sito, hasta el t&eacute;rmino requerido y permitido por la ley con el fin de dar aplicaci&oacute;n a las disposiciones aplicables de retenci&oacute;n de informaci&oacute;n.</p>
                    <p>Cuando el prop&oacute;sito para el cual la informaci&oacute;n fue recolectada haya cesado, dicha informaci&oacute;n ser&aacute; separada a una base de datos distinta y almacenada por cierto periodo de tiempo por razones de protecci&oacute;n de informaci&oacute;n de acuerdo a las pol&iacute;ticas internas de CONTINENTAL y otras leyes y disposiciones aplicables.</p>
                    <p>Para la destrucci&oacute;n de la informaci&oacute;n personal suministrada por los usuarios, CONTINENTAL tomar&aacute; todas las medidas necesarias para garantizar que la reproducci&oacute;n o recuperaci&oacute;n f&iacute;sica o digital de la misma no sea posible.</p>
                    <p><b>Uso adicionales</b><br />
                        La informaci&oacute;n suministrada durante el proceso de registro, inscripci&oacute;n a alg&uacute;n programa y promociones, se emplea de forma agregada para realizar estudios internos sobre los datos demogr&aacute;ficos, intereses y comportamiento de los usuarios; con la finalidad de proporcionarles productos, servicios y contenidos acordes a sus necesidades.</p>
                    <p><b>Protecci&oacute;n</b><br />
                        A pesar de contar cada d&iacute;a con herramientas m&aacute;s seguras, la protecci&oacute;n de los datos enviados a trav&eacute;s de Internet no se puede garantizar al 100%; por lo que una vez recibidos, se har&aacute; todo lo posible por salvaguardar la informaci&oacute;n.</p>
                    <p>El usuario es responsable de mantener la confidencialidad del usuario y contrase&ntilde;a para el ingreso al portal electr&oacute;nico www.contiplus.net. El usuario es responsable de los usos relacionados con su usuario y contrase&ntilde;a a trav&eacute;s del portal electr&oacute;nico www.contiplus.net, incluso en los casos en que dichos usos no hayan sido por &eacute;l autorizados.&nbsp;</p>
                    <p><b>Cookies</b><br />
                        Las cookies son peque&ntilde;as piezas de informaci&oacute;n que son enviadas por el sitio web al navegador.</p>
                    <p>Se almacenan en el disco duro de los equipos y utilizan para determinar las preferencias de los usuarios que acceden al portal electr&oacute;nico (www.contiplus.net), as&iacute; como para rastrear determinados comportamientos o actividades.</p>
                    <p>Las cookies permiten reconocer a los usuarios, detectar el ancho de banda que han seleccionado, identificar la informaci&oacute;n m&aacute;s destacada, calcular el tama&ntilde;o de la audiencia y medir algunos par&aacute;metros de tr&aacute;fico.</p>
                    <p><b>Confidencialidad</b><br />
                        Cuando el usuario se encuentre en el sitio web (www.contiplus.net), compartir&aacute; su informaci&oacute;n, salvo que se especifique lo contrario.</p>
                    <p>CONTINENTAL, no tiene obligaci&oacute;n alguna de mantener confidencial cualquier otra informaci&oacute;n que el usuario proporcione por medio de boletines y pl&aacute;ticas en l&iacute;nea (chats), as&iacute; como a trav&eacute;s de las cookies.</p>
                    <p>S&oacute;lo se podr&aacute; difundir la informaci&oacute;n en casos especiales, como identificar, localizar o realizar acciones legales contra aquellas personas que infrinjan las condiciones de servicio del sitio web (www.contiplus.net), causen da&ntilde;os a, o interfieran en, los derechos de CONTINENTAL, sus propiedades, de otros usuarios del portal o de cualquier persona que pudiese resultar perjudicada por dichas acciones.</p>
                    <p>CONTINENTAL NO vender&aacute;, regalar&aacute;, facilitar&aacute; ni alquilar&aacute; informaci&oacute;n confidencial a terceros. Si el usuario no desea que sus datos sean compartidos, podr&aacute; prescindir de un servicio determinado o abstenerse de participar en algunas actividades.</p>
                    <p>CONTINENTAL NO compartir&aacute; informaci&oacute;n confidencial con terceras partes, salvo expresa autorizaci&oacute;n de sus suscriptores o cuando por medio de una orden judicial se requiera para cumplir con ciertas disposiciones procesales.</p>
                    <p><b>Modificaciones en las Pol&iacute;ticas de Privacidad</b><br />
                        CONTINENTAL se reserva el derecho de efectuar en cualquier momento, modificaciones en las presentes pol&iacute;ticas de privacidad y adaptarlas a novedades legislativas, jurisprudenciales, as&iacute; como a pr&aacute;cticas del mercado. Las modificaciones sustanciales de la Pol&iacute;tica de Privacidad ser&aacute;n comunicadas al Titular antes o a m&aacute;s tardar al momento de implementar la modificaci&oacute;n. Cuando la modificaci&oacute;n verse sobre la finalidad del tratamiento de la informaci&oacute;n, CONTINENTAL solicitar&aacute; una nueva autorizaci&oacute;n al Titular de la informaci&oacute;n. .<br />
                        <b>Vigencia</b><br />
                        La presente Pol&iacute;tica de Privacidad se encuentra vigente desde el [incluir fecha].</p>
                </div>
            </div>
        </div>
    </div>
    <?php
}
