<div class="title-page terms-section">
    <?php if ($language == IS_ESPANIOL) { ?>
        P&oacute;litica de privacidad para M&eacute;xico
    <?php } else { ?>
        PRIVACY POLICY
    <?php } ?>
    <?php echo __('', true); ?>
</div>
<div class="full-page">
    <div class="data-page">        
        <div class="data-section">
            <div class="terms-data">                
                <?php if ($language == IS_ESPANIOL) { ?>
                    <p>CONTINENTAL bajo responsabilidad de Contitech Mexicana, S.A. de C.V. se compromete a asegurar la privacidad de la informaci&oacute;n personal y profesional obtenida a trav&eacute;s de sus servicios en l&iacute;nea. No obstante, se sugiere leer la normativa descrita a continuaci&oacute;n para entender el tratamiento de los datos proporcionados.</p>
                    <p><b>Protecci&oacute;n de Datos Personales</b><br />
                        Contitech Mexicana, S.A. de C.V. y/o empresas filiales y subsidiarias, con domicilio en la calle Av. Santa Fe 170, piso 7, Colonia Lomas de Santa Fe, en M&eacute;xico, Distrito Federal, es responsable de la confidencialidad, uso y protecci&oacute;n de la informaci&oacute;n personal que el usuario llegar&eacute; a proporcionar a trav&eacute;s del uso del sitio de Internet www.contiplus.net. Por lo anterior su informaci&oacute;n personal ser&aacute; utilizada para fines de contacto y de identificaci&oacute;n en cualquier tipo de relaci&oacute;n jur&iacute;dica que realice con nosotros, as&iacute; como para generar el usuario y contrase&ntilde;a requerido para acceder a los servicios ofrecidos a trav&eacute;s del portal de Internet www.contiplus.net.</p>
                    <p>Para las finalidades anteriores, podr&iacute;amos requerirle su nombre, direcci&oacute;n, tel&eacute;fono, correo electr&oacute;nico y informaci&oacute;n profesional. Para el caso que se desee limitar el uso o divulgaci&oacute;n de su informaci&oacute;n personal, ejercitar sus derechos de acceso, actualizaci&oacute;n, rectificaci&oacute;n, cancelaci&oacute;n o supresi&oacute;n de sus datos personales, as&iacute; como de oposici&oacute;n al tratamiento de los mismos y revocar el consentimiento que para tal fin nos haya otorgado, lo podr&aacute; realizar a trav&eacute;s del siguiente canal de atenci&oacute;n: a trav&eacute;s de nuestro correo electr&oacute;nico www.contiplus.net en cuyo caso se le informar&aacute; los procedimientos a seguir.</p>
                    <p>Cualquier tipo de informaci&oacute;n personal recolectada u obtenida s&oacute;lo ser&aacute; tratada, usada, divulgada o transferida dentro de los l&iacute;mites permitidos por las disposiciones legales de cada jurisdicci&oacute;n en observancia de la presente Pol&iacute;tica de Privacidad o seg&uacute;n como sea definido e informado en cada momento espec&iacute;fico en que se realice la recolecci&oacute;n de datos personales. Le informamos que sus datos personales no ser&aacute;n transferidos a terceros para fines distintos a los aqu&iacute; descritos salvo a aquellos subcontratados por CONTINENTAL para el almacenamiento de los mismos, salvaguardando su protecci&oacute;n y confidencialidad, sin que para ello sea necesario obtener su autorizaci&oacute;n. Usted puede acceder a la lista de los receptores de la informaci&oacute;n visitando [incluir link].</p>
                    <p>Para verificar los candados de seguridad SSL, cookies y otras herramientas de rastreo favor de visitar &ldquo;seguridad del sitio&rdquo;. Para verificar los cambios al presente aviso, lo podr&aacute; realizar en la p&aacute;gina www.contiplus.net</p>
                    <p><b>Tipo de informaci&oacute;n</b><br />
                        Se recopilar&aacute; la informaci&oacute;n de diferentes formas y desde distintas &aacute;reas del sitio web www.contiplus.net</p>
                    <p>Se sujetar&aacute;n a las normas de seguridad y privacidad todos aquellos datos personales cuya recolecci&oacute;n hayan sido autorizados por el usuario de forma previa y voluntariamente en dicha direcci&oacute;n electr&oacute;nica.</p>
                    <p>Se solicitar&aacute; informaci&oacute;n como:<br />
                        -&nbsp;&nbsp; &nbsp;Nombre (s) y apellidos.<br />
                        -&nbsp;&nbsp; &nbsp;Correo electr&oacute;nico.<br />
                        -&nbsp;&nbsp; &nbsp;Tel&eacute;fono.<br />
                        -&nbsp;&nbsp; &nbsp;Datos profesionales.</p>
                    <p>La informaci&oacute;n solicitada permitir&aacute; contactar a los usuarios cuando sea necesario. Los usuarios podr&aacute;n ser contactados por tel&eacute;fono o correo electr&oacute;nico en caso de que se requieran datos adicionales para completar alguna solicitud, en cuyo caso, de tratarse de datos personales, ser&aacute; requerida una autorizaci&oacute;n adicional.</p>
                    <p><b>Retenci&oacute;n, supresi&oacute;n y destrucci&oacute;n de la informaci&oacute;n</b></p>
                    <p>CONTINENTAL s&oacute;lo retendr&aacute; sus datos personales hasta que el prop&oacute;sito para el que fueron recolectados sea cumplido y una vez finalizado dicho prop&oacute;sito, hasta el t&eacute;rmino requerido y permitido por la ley con el fin de dar aplicaci&oacute;n a las disposiciones aplicables de retenci&oacute;n de informaci&oacute;n.</p>
                    <p>Cuando el prop&oacute;sito para el cual la informaci&oacute;n fue recolectada haya cesado, dicha informaci&oacute;n ser&aacute; separada a una base de datos distinta y almacenada por cierto periodo de tiempo por razones de protecci&oacute;n de informaci&oacute;n de acuerdo a las pol&iacute;ticas internas de CONTINENTAL y otras leyes y disposiciones aplicables.</p>
                    <p>Para la destrucci&oacute;n de la informaci&oacute;n personal suministrada por los usuarios, CONTINENTAL tomar&aacute; todas las medidas necesarias para garantizar que la reproducci&oacute;n o recuperaci&oacute;n f&iacute;sica o digital de la misma no sea posible.</p>
                    <p><b>Uso adicionales</b><br />
                        La informaci&oacute;n suministrada durante el proceso de registro, inscripci&oacute;n a alg&uacute;n programa y promociones, se emplea de forma agregada para realizar estudios internos sobre los datos demogr&aacute;ficos, intereses y comportamiento de los usuarios; con la finalidad de proporcionarles productos, servicios y contenidos acordes a sus necesidades.</p>
                    <p><b>Protecci&oacute;n</b><br />
                        A pesar de contar cada d&iacute;a con herramientas m&aacute;s seguras, la protecci&oacute;n de los datos enviados a trav&eacute;s de Internet no se puede garantizar al 100%; por lo que una vez recibidos, se har&aacute; todo lo posible por salvaguardar la informaci&oacute;n.</p>
                    <p>El usuario es responsable de mantener la confidencialidad del usuario y contrase&ntilde;a para el ingreso al portal electr&oacute;nico www.contiplus.net. El usuario es responsable de los usos relacionados con su usuario y contrase&ntilde;a a trav&eacute;s del portal electr&oacute;nico www.contiplus.net, incluso en los casos en que dichos usos no hayan sido por &eacute;l autorizados.&nbsp;</p>
                    <p><b>Cookies</b><br />
                        Las cookies son peque&ntilde;as piezas de informaci&oacute;n que son enviadas por el sitio web al navegador.</p>
                    <p>Se almacenan en el disco duro de los equipos y utilizan para determinar las preferencias de los usuarios que acceden al portal electr&oacute;nico (www.contiplus.net), as&iacute; como para rastrear determinados comportamientos o actividades.</p>
                    <p>Las cookies permiten reconocer a los usuarios, detectar el ancho de banda que han seleccionado, identificar la informaci&oacute;n m&aacute;s destacada, calcular el tama&ntilde;o de la audiencia y medir algunos par&aacute;metros de tr&aacute;fico.</p>
                    <p><b>Confidencialidad</b><br />
                        Cuando el usuario se encuentre en el sitio web (www.contiplus.net), compartir&aacute; su informaci&oacute;n, salvo que se especifique lo contrario.</p>
                    <p>CONTINENTAL, no tiene obligaci&oacute;n alguna de mantener confidencial cualquier otra informaci&oacute;n que el usuario proporcione por medio de boletines y pl&aacute;ticas en l&iacute;nea (chats), as&iacute; como a trav&eacute;s de las cookies.</p>
                    <p>S&oacute;lo se podr&aacute; difundir la informaci&oacute;n en casos especiales, como identificar, localizar o realizar acciones legales contra aquellas personas que infrinjan las condiciones de servicio del sitio web (www.contiplus.net), causen da&ntilde;os a, o interfieran en, los derechos de CONTINENTAL, sus propiedades, de otros usuarios del portal o de cualquier persona que pudiese resultar perjudicada por dichas acciones.</p>
                    <p>CONTINENTAL NO vender&aacute;, regalar&aacute;, facilitar&aacute; ni alquilar&aacute; informaci&oacute;n confidencial a terceros. Si el usuario no desea que sus datos sean compartidos, podr&aacute; prescindir de un servicio determinado o abstenerse de participar en algunas actividades.</p>
                    <p>CONTINENTAL NO compartir&aacute; informaci&oacute;n confidencial con terceras partes, salvo expresa autorizaci&oacute;n de sus suscriptores o cuando por medio de una orden judicial se requiera para cumplir con ciertas disposiciones procesales.</p>
                    <p><b>Modificaciones en las Pol&iacute;ticas de Privacidad</b><br />
                        CONTINENTAL se reserva el derecho de efectuar en cualquier momento, modificaciones en las presentes pol&iacute;ticas de privacidad y adaptarlas a novedades legislativas, jurisprudenciales, as&iacute; como a pr&aacute;cticas del mercado. Las modificaciones sustanciales de la Pol&iacute;tica de Privacidad ser&aacute;n comunicadas al Titular antes o a m&aacute;s tardar al momento de implementar la modificaci&oacute;n. Cuando la modificaci&oacute;n verse sobre la finalidad del tratamiento de la informaci&oacute;n, CONTINENTAL solicitar&aacute; una nueva autorizaci&oacute;n al Titular de la informaci&oacute;n. .<br />
                        <b>Vigencia</b><br />
                        La presente Pol&iacute;tica de Privacidad se encuentra vigente desde el 01 de Enero de 2014.</p>                
                <?php } else { ?>
                    <p>The website located at www.contiplus.net (the “Website”) and the CONTI+ mobile application (the “App,” and collectively with the Website, the “Offerings”) are operated by ContiTech USA, Inc. (“Continental”, “we,” “us,” or “our). This Privacy Policy explains how we collect and use personally identifiable information and non-identifying information about you when you access or use the Offerings.</p>
                    <p>Please read this page carefully. By accessing the Offerings or submitting your Personal Information (defined below) in order to receive the Offerings, you agree to the terms set forth in this Privacy Policy. IF YOU DO NOT ACCEPT THE TERMS OF THIS PRIVACY POLICY, DO NOT ACCESS OR USE THE OFFERINGS.</p>
                    <p>Continental will notify you of any changes to this Privacy Policy by posting the modified Privacy Policy and its effective date on this page. Accordingly, you should visit this page periodically to identify and understand any such changes. By continuing to access or use the Offerings after a modification, you agree to be bound by the modified Privacy Policy.</p>
                    <p><b>1. INFORMATION COLLECTED BY CONTINENTAL</b></p>
                    <p><b>a. Collection of Personal Information</b></p>
                    <p>“Personal Information” means all personally-identifiable information (such as your name, physical address, e-mail address, or telephone numbers) that you submit in connection with the Offerings. Continental does not collect Personal Information unless you voluntarily submit it in connection with your use of the Offerings, send inquiries to Continental, or participate in certain activities available via the Offerings. We collect Personal Information when you choose to use certain features of the Offerings, including when you create an account on the Website or the App.</p>
                    <p><b>b. Information Gathered Automatically</b></p>
                    <p>Continental automatically collects certain non-identifying information about you (such as your movement about the Website or App, the pages you visit most frequently, the type of browser or computer operating system you use, or the domain name of the website from which you link). Continental uses “cookies” to customize and improve your use of the Offerings. Cookies are small pieces of information or data stored on your computer or mobile device that are used to determine your preferences and track certain behavior or activities when you use the Offerings. If you object to this practice, you may erase or block cookies. We recommend, however, that you allow cookies to be stored on your computer or mobile device as they may be needed to properly use the Offerings.</p>
                    <p><b>c. Your Content</b></p>
                    <p>Continental assumes no responsibility for securing any other content you submit via the Offerings. Continental has no obligation to use, or solicit or enable others to use any content you submit to us.</p>
                    <p><b>2. CHANGING OR REMOVING YOUR PERSONAL INFORMATION</b></p>
                    <p>Continental will retain any Personal Information that you submit in connection with your account unless Continental deems such Personal Information to violate this Agreement or until such time as you decide
                        to remove such Personal Information. You understand that deleted Personal Information may persist for a reasonable period of time in backup copies but will not be available to others.</p>
                    <p>If you wish to review, change, or remove any Personal Information that you have provided in connection with the Offerings, or if you wish to delete your account with us, please email us at [<a href="mailto:simon.bishop@fluid.contitech.co.uk">simon.bishop@fluid.contitech.co.uk</a>].</p>
                    <p><b>3. USE OR DISCLOSURE OF PERSONAL INFORMATION</b></p>
                    <p>Continental may use your Personal Information to contact you regarding the Offerings. We may also use your Personal Information to provide services requested by you and for internal research and marketing purposes. We may share your Personal Information and non-identifying information that we collect from you with our parent, subsidiaries, divisions, or affiliates.</p>
                    <p>Continental will not use, disclose, or sell your Personal information to any third parties for any purposes other than those necessary to deliver the Offerings. Otherwise, we will not sell or transfer to unaffiliated third parties any Personal Information that you submit or any non-identifying information collected without your consent.</p>
                    <p>The Personal Information and non-identifying information we collect from you may be used as follows:<br />
                        i. to personalize your experience and better respond to your individual needs;<br />
                        ii. to improve the Offerings;<br />
                        iii. to improve customer service;<br />
                        iv. to administer contests, promotions, surveys or other features for the Offerings;<br/>
                        v. to send periodic mailings concerning information and updates pertaining to Continental;<br/>
                        vi. to send special or promotional offers or discounts related to Continental or its affiliates and information related to products you have viewed via the Offerings; or<br/>
                        vii. as an asset in connection with a proposed or actual merger or sale (including any transfers made as part of an insolvency or bankruptcy proceeding) involving all or part of our business or as part of a corporate reorganization, stock sale or other change in control.</p>
                    <p>Notwithstanding the foregoing or any other statements or representations here or elsewhere, Continental reserves the right to disclose any Personal Information in our possession if Continental believes that such disclosure is necessary: (i) to conform to legal requirements or to respond to a subpoena, search warrant, or other legal process received by Continental, whether or not a response is required by applicable law; (ii) to enforce or protect Continental’s rights; or (iii) to protect the safety of users of Continental’s Offerings and members of the general public.</p>
                    <p>WE ARE NOT RESPONSIBLE FOR THE PERSONAL INFORMATION AND OTHER NON-IDENTIFYING INFORMATION YOU CHOOSE TO SUBMIT IN ANY PUBLICLY ACCESSIBLE AREA OF THE OFFERINGS.</p>
                    <p><b>4. SECURITY</b></p>
                    <p>Continental has reasonable security measures in place to protect Personal Information you submit in order to receive the Offerings. While no computer system or server is completely secure, we believe the measures we implement reduce security problems. Notwithstanding the foregoing, Continental cannot guarantee the security of your Personal Information. When you communicate with Continental electronically or otherwise submit your Personal Information, your communication is not necessarily secure and is subject to all of the risks of communication, including unauthorized entry or use, hardware or software failure, and other factors that may compromise the security of Personal Information at any time. Continental assumes no responsibility for the security of any Personal Information you submit.</p>
                    <p><b>5. LINKS</b></p>
                    <p>We may permit certain third parties to link to our Offerings, and the Offerings may contain links to third- party sites. Continental is not responsible for the privacy policies or practices of such third parties, including on such third parties’ websites. When linking to a third party website, you should read the privacy policy stated on that website. This Privacy Policy only governs Personal Information, non- identifying information and content collected in connection with the Offerings.</p>
                    <p><b>6. ADDITIONAL PROTECTIONS FOR CHILDREN</b></p>
                    <p>The Offerings are not designed for or targeted to children under the age of 13, and Continental will never knowingly solicit or collect the Personal Information of a child under the age of 13. If we discover that Personal Information of a child under the age of 13 has been submitted without verifiable parental consent, we will immediately delete such Personal Information.</p>
                    <p>7. CONTACT INFORMATION</p>
                    <p>If you have any questions about this Privacy Policy or your dealings with Continental, please feel free to contact us at:</p>
                    <p>ContiTech USA, Inc.<br/>
                        703 S. Cleveland Massillon Road<br/> Fairlawn, Ohio 44333</p>
                    <p>E-mail: [<a href="mailto:simon.bishop@fluid.contitech.co.uk">simon.bishop@fluid.contitech.co.uk</a>]</p>
                    <p>Effective date: 5 / 17 / 2017</p>
                <?php } ?>
            </div>
        </div>
    </div>
</div>
<?php if ($language == IS_ESPANIOL) { ?>
    <div class="title-page terms-section">
        P&oacute;litica de privacidad para Colombia
    </div>   
    <div class="full-page">
        <div class="data-page">        
            <div class="data-section">
                <div class="terms-data">
                    <p>CONTINENTAL bajo responsabilidad de Contitech Mexicana, S.A. de C.V. se compromete a asegurar la privacidad de la informaci&oacute;n personal y profesional obtenida a trav&eacute;s de sus servicios en l&iacute;nea. No obstante, se sugiere leer la normativa descrita a continuaci&oacute;n para entender el tratamiento de los datos proporcionados.</p>
                    <p><b>Protecci&oacute;n de Datos Personales</b><br />
                        Contitech Mexicana, S.A. de C.V. y/o empresas filiales y subsidiarias, con domicilio en la calle Av. Santa Fe 170, piso 7, Colonia Lomas de Santa Fe, en M&eacute;xico, Distrito Federal, es responsable de la confidencialidad, uso y protecci&oacute;n de la informaci&oacute;n personal que el usuario llegar&eacute; a proporcionar a trav&eacute;s del uso del sitio de Internet www.contiplus.net. Por lo anterior su informaci&oacute;n personal ser&aacute; utilizada para fines de contacto y de identificaci&oacute;n en cualquier tipo de relaci&oacute;n jur&iacute;dica que realice con nosotros, as&iacute; como para generar el usuario y contrase&ntilde;a requerido para acceder a los servicios ofrecidos a trav&eacute;s del portal de Internet www.contiplus.net.</p>
                    <p>Para las finalidades anteriores, podr&iacute;amos requerirle su nombre, direcci&oacute;n, tel&eacute;fono, correo electr&oacute;nico y informaci&oacute;n profesional. Para el caso que se desee limitar el uso o divulgaci&oacute;n de su informaci&oacute;n personal, ejercitar sus derechos de acceso, actualizaci&oacute;n, rectificaci&oacute;n, cancelaci&oacute;n o supresi&oacute;n de sus datos personales, as&iacute; como de oposici&oacute;n al tratamiento de los mismos y revocar el consentimiento que para tal fin nos haya otorgado, lo podr&aacute; realizar a trav&eacute;s del siguiente canal de atenci&oacute;n: a trav&eacute;s de nuestro correo electr&oacute;nico <b>www.contiplus.net</b> en cuyo caso se le informar&aacute; los procedimientos a seguir.</p>
                    <p>Cualquier tipo de informaci&oacute;n personal recolectada u obtenida s&oacute;lo ser&aacute; tratada, usada, divulgada o transferida dentro de los l&iacute;mites permitidos por las disposiciones legales de cada jurisdicci&oacute;n en observancia de la presente Pol&iacute;tica de Privacidad o seg&uacute;n como sea definido e informado en cada momento espec&iacute;fico en que se realice la recolecci&oacute;n de datos personales. Le informamos que sus datos personales no ser&aacute;n transferidos a terceros para fines distintos a los aqu&iacute; descritos salvo a aquellos subcontratados por CONTINENTAL para el almacenamiento de los mismos, salvaguardando su protecci&oacute;n y confidencialidad, sin que para ello sea necesario obtener su autorizaci&oacute;n. Usted puede acceder a la lista de los receptores de la informaci&oacute;n visitando [incluir link].</p>
                    <p>Para verificar los candados de seguridad SSL, cookies y otras herramientas de rastreo favor de visitar &ldquo;seguridad del sitio&rdquo;. Para verificar los cambios al presente aviso, lo podr&aacute; realizar en la p&aacute;gina www.contiplus.net</p>
                    <p><b>Tipo de informaci&oacute;n</b><br />
                        Se recopilar&aacute; la informaci&oacute;n de diferentes formas y desde distintas &aacute;reas del sitio web www.contiplus.net</p>
                    <p>Se sujetar&aacute;n a las normas de seguridad y privacidad todos aquellos datos personales cuya recolecci&oacute;n hayan sido autorizados por el usuario de forma previa y voluntariamente en dicha direcci&oacute;n electr&oacute;nica.</p>
                    <p>Se solicitar&aacute; informaci&oacute;n como:<br />
                        -&nbsp;&nbsp; &nbsp;Nombre (s) y apellidos.<br />
                        -&nbsp;&nbsp; &nbsp;Correo electr&oacute;nico.<br />
                        -&nbsp;&nbsp; &nbsp;Tel&eacute;fono.<br />
                        -&nbsp;&nbsp; &nbsp;Datos profesionales.</p>
                    <p>La informaci&oacute;n solicitada permitir&aacute; contactar a los usuarios cuando sea necesario. Los usuarios podr&aacute;n ser contactados por tel&eacute;fono o correo electr&oacute;nico en caso de que se requieran datos adicionales para completar alguna solicitud, en cuyo caso, de tratarse de datos personales, ser&aacute; requerida una autorizaci&oacute;n adicional.</p>
                    <p><b>Retenci&oacute;n, supresi&oacute;n y destrucci&oacute;n de la informaci&oacute;n</b></p>
                    <p>CONTINENTAL s&oacute;lo retendr&aacute; sus datos personales hasta que el prop&oacute;sito para el que fueron recolectados sea cumplido y una vez finalizado dicho prop&oacute;sito, hasta el t&eacute;rmino requerido y permitido por la ley con el fin de dar aplicaci&oacute;n a las disposiciones aplicables de retenci&oacute;n de informaci&oacute;n.</p>
                    <p>Cuando el prop&oacute;sito para el cual la informaci&oacute;n fue recolectada haya cesado, dicha informaci&oacute;n ser&aacute; separada a una base de datos distinta y almacenada por cierto periodo de tiempo por razones de protecci&oacute;n de informaci&oacute;n de acuerdo a las pol&iacute;ticas internas de CONTINENTAL y otras leyes y disposiciones aplicables.</p>
                    <p>Para la destrucci&oacute;n de la informaci&oacute;n personal suministrada por los usuarios, CONTINENTAL tomar&aacute; todas las medidas necesarias para garantizar que la reproducci&oacute;n o recuperaci&oacute;n f&iacute;sica o digital de la misma no sea posible.</p>
                    <p><b>Uso adicionales</b><br />
                        La informaci&oacute;n suministrada durante el proceso de registro, inscripci&oacute;n a alg&uacute;n programa y promociones, se emplea de forma agregada para realizar estudios internos sobre los datos demogr&aacute;ficos, intereses y comportamiento de los usuarios; con la finalidad de proporcionarles productos, servicios y contenidos acordes a sus necesidades.</p>
                    <p><b>Protecci&oacute;n</b><br />
                        A pesar de contar cada d&iacute;a con herramientas m&aacute;s seguras, la protecci&oacute;n de los datos enviados a trav&eacute;s de Internet no se puede garantizar al 100%; por lo que una vez recibidos, se har&aacute; todo lo posible por salvaguardar la informaci&oacute;n.</p>
                    <p>El usuario es responsable de mantener la confidencialidad del usuario y contrase&ntilde;a para el ingreso al portal electr&oacute;nico www.contiplus.net. El usuario es responsable de los usos relacionados con su usuario y contrase&ntilde;a a trav&eacute;s del portal electr&oacute;nico www.contiplus.net, incluso en los casos en que dichos usos no hayan sido por &eacute;l autorizados.&nbsp;</p>
                    <p><b>Cookies</b><br />
                        Las cookies son peque&ntilde;as piezas de informaci&oacute;n que son enviadas por el sitio web al navegador.</p>
                    <p>Se almacenan en el disco duro de los equipos y utilizan para determinar las preferencias de los usuarios que acceden al portal electr&oacute;nico (www.contiplus.net), as&iacute; como para rastrear determinados comportamientos o actividades.</p>
                    <p>Las cookies permiten reconocer a los usuarios, detectar el ancho de banda que han seleccionado, identificar la informaci&oacute;n m&aacute;s destacada, calcular el tama&ntilde;o de la audiencia y medir algunos par&aacute;metros de tr&aacute;fico.</p>
                    <p><b>Confidencialidad</b><br />
                        Cuando el usuario se encuentre en el sitio web (www.contiplus.net), compartir&aacute; su informaci&oacute;n, salvo que se especifique lo contrario.</p>
                    <p>CONTINENTAL, no tiene obligaci&oacute;n alguna de mantener confidencial cualquier otra informaci&oacute;n que el usuario proporcione por medio de boletines y pl&aacute;ticas en l&iacute;nea (chats), as&iacute; como a trav&eacute;s de las cookies.</p>
                    <p>S&oacute;lo se podr&aacute; difundir la informaci&oacute;n en casos especiales, como identificar, localizar o realizar acciones legales contra aquellas personas que infrinjan las condiciones de servicio del sitio web (www.contiplus.net), causen da&ntilde;os a, o interfieran en, los derechos de CONTINENTAL, sus propiedades, de otros usuarios del portal o de cualquier persona que pudiese resultar perjudicada por dichas acciones.</p>
                    <p>CONTINENTAL NO vender&aacute;, regalar&aacute;, facilitar&aacute; ni alquilar&aacute; informaci&oacute;n confidencial a terceros. Si el usuario no desea que sus datos sean compartidos, podr&aacute; prescindir de un servicio determinado o abstenerse de participar en algunas actividades.</p>
                    <p>CONTINENTAL NO compartir&aacute; informaci&oacute;n confidencial con terceras partes, salvo expresa autorizaci&oacute;n de sus suscriptores o cuando por medio de una orden judicial se requiera para cumplir con ciertas disposiciones procesales.</p>
                    <p><b>Modificaciones en las Pol&iacute;ticas de Privacidad</b><br />
                        CONTINENTAL se reserva el derecho de efectuar en cualquier momento, modificaciones en las presentes pol&iacute;ticas de privacidad y adaptarlas a novedades legislativas, jurisprudenciales, as&iacute; como a pr&aacute;cticas del mercado. Las modificaciones sustanciales de la Pol&iacute;tica de Privacidad ser&aacute;n comunicadas al Titular antes o a m&aacute;s tardar al momento de implementar la modificaci&oacute;n. Cuando la modificaci&oacute;n verse sobre la finalidad del tratamiento de la informaci&oacute;n, CONTINENTAL solicitar&aacute; una nueva autorizaci&oacute;n al Titular de la informaci&oacute;n. .<br />
                        <b>Vigencia</b><br />
                        La presente Pol&iacute;tica de Privacidad se encuentra vigente desde el [incluir fecha].</p>
                </div>
            </div>
        </div>
    </div>
    <div class="title-page terms-section">
        P&oacute;litica de privacidad para Argentina
    </div>   
    <div class="full-page">
        <div class="data-page">        
            <div class="data-section">
                <div class="terms-data">
                    <p>CONTINENTAL bajo responsabilidad de Contitech Mexicana, S.A. de C.V. se compromete a asegurar la privacidad de la informaci&oacute;n personal y profesional obtenida a trav&eacute;s de sus servicios en l&iacute;nea. No obstante, se sugiere leer la normativa descrita a continuaci&oacute;n para entender el tratamiento de los datos proporcionados.</p>
                    <p><b>Protecci&oacute;n de Datos Personales</b><br />
                        Contitech Mexicana, S.A. de C.V. y/o empresas filiales y subsidiarias, con domicilio en la calle Av. Santa Fe 170, piso 7, Colonia Lomas de Santa Fe, en M&eacute;xico, Distrito Federal, es responsable de la confidencialidad, uso y protecci&oacute;n de la informaci&oacute;n personal que el usuario llegar&eacute; a proporcionar a trav&eacute;s del uso del sitio de Internet www.contiplus.net. Por lo anterior su informaci&oacute;n personal ser&aacute; utilizada para fines de contacto y de identificaci&oacute;n en cualquier tipo de relaci&oacute;n jur&iacute;dica que realice con nosotros, as&iacute; como para generar el usuario y contrase&ntilde;a requerido para acceder a los servicios ofrecidos a trav&eacute;s del portal de Internet www.contiplus.net.</p>
                    <p>Para las finalidades anteriores, podr&iacute;amos requerirle su nombre, direcci&oacute;n, tel&eacute;fono, correo electr&oacute;nico y informaci&oacute;n profesional. Para el caso que se desee limitar el uso o divulgaci&oacute;n de su informaci&oacute;n personal, ejercitar sus derechos de acceso, actualizaci&oacute;n, rectificaci&oacute;n, cancelaci&oacute;n o supresi&oacute;n de sus datos personales, as&iacute; como de oposici&oacute;n al tratamiento de los mismos y revocar el consentimiento que para tal fin nos haya otorgado, lo podr&aacute; realizar a trav&eacute;s del siguiente canal de atenci&oacute;n: a trav&eacute;s de nuestro correo electr&oacute;nico:admin@contiplus.net,,en cuyo caso se le informar&aacute; los procedimientos a seguir.</p>
                    <p>Cualquier tipo de informaci&oacute;n personal recolectada u obtenida s&oacute;lo ser&aacute; tratada, usada, divulgada o transferida dentro de los l&iacute;mites permitidos por las disposiciones legales de cada jurisdicci&oacute;n en observancia de la presente Pol&iacute;tica de Privacidad o seg&uacute;n como sea definido e informado en cada momento espec&iacute;fico en que se realice la recolecci&oacute;n de datos personales. Le informamos que sus datos personales no ser&aacute;n transferidos a terceros para fines distintos a los aqu&iacute; descritos salvo a aquellos subcontratados por CONTINENTAL para el almacenamiento de los mismos, salvaguardando su protecci&oacute;n y confidencialidad, sin que para ello sea necesario obtener su autorizaci&oacute;n. Usted puede acceder a la lista de los receptores de la informaci&oacute;n visitando [incluir link].</p>
                    <p>Para verificar los candados de seguridad SSL, cookies y otras herramientas de rastreo favor de visitar &ldquo;seguridad del sitio&rdquo;. Para verificar los cambios al presente aviso, lo podr&aacute; realizar en la p&aacute;gina www.contiplus.net</p>
                    <p><b>Tipo de informaci&oacute;n</b><br />
                        Se recopilar&aacute; la informaci&oacute;n de diferentes formas y desde distintas &aacute;reas del sitio web www.contiplus.net</p>
                    <p>Se sujetar&aacute;n a las normas de seguridad y privacidad todos aquellos datos personales cuya recolecci&oacute;n hayan sido autorizados por el usuario de forma previa y voluntariamente en dicha direcci&oacute;n electr&oacute;nica.</p>
                    <p>Se solicitar&aacute; informaci&oacute;n como:<br />
                        -&nbsp;&nbsp; &nbsp;Nombre (s) y apellidos.<br />
                        -&nbsp;&nbsp; &nbsp;Correo electr&oacute;nico.<br />
                        -&nbsp;&nbsp; &nbsp;Tel&eacute;fono.<br />
                        -&nbsp;&nbsp; &nbsp;Datos profesionales.</p>
                    <p>La informaci&oacute;n solicitada permitir&aacute; contactar a los usuarios cuando sea necesario. Los usuarios podr&aacute;n ser contactados por tel&eacute;fono o correo electr&oacute;nico en caso de que se requieran datos adicionales para completar alguna solicitud, en cuyo caso, de tratarse de datos personales, ser&aacute; requerida una autorizaci&oacute;n adicional.</p>
                    <p><b>Retenci&oacute;n, supresi&oacute;n y destrucci&oacute;n de la informaci&oacute;n</b></p>
                    <p>CONTINENTAL s&oacute;lo retendr&aacute; sus datos personales hasta que el prop&oacute;sito para el que fueron recolectados sea cumplido y una vez finalizado dicho prop&oacute;sito, hasta el t&eacute;rmino requerido y permitido por la ley con el fin de dar aplicaci&oacute;n a las disposiciones aplicables de retenci&oacute;n de informaci&oacute;n.</p>
                    <p>Cuando el prop&oacute;sito para el cual la informaci&oacute;n fue recolectada haya cesado, dicha informaci&oacute;n ser&aacute; separada a una base de datos distinta y almacenada por cierto periodo de tiempo por razones de protecci&oacute;n de informaci&oacute;n de acuerdo a las pol&iacute;ticas internas de CONTINENTAL y otras leyes y disposiciones aplicables.</p>
                    <p>Para la destrucci&oacute;n de la informaci&oacute;n personal suministrada por los usuarios, CONTINENTAL tomar&aacute; todas las medidas necesarias para garantizar que la reproducci&oacute;n o recuperaci&oacute;n f&iacute;sica o digital de la misma no sea posible.</p>
                    <p><b>Uso adicionales</b><br />
                        La informaci&oacute;n suministrada durante el proceso de registro, inscripci&oacute;n a alg&uacute;n programa y promociones, se emplea de forma agregada para realizar estudios internos sobre los datos demogr&aacute;ficos, intereses y comportamiento de los usuarios; con la finalidad de proporcionarles productos, servicios y contenidos acordes a sus necesidades.</p>
                    <p><b>Protecci&oacute;n</b><br />
                        A pesar de contar cada d&iacute;a con herramientas m&aacute;s seguras, la protecci&oacute;n de los datos enviados a trav&eacute;s de Internet no se puede garantizar al 100%; por lo que una vez recibidos, se har&aacute; todo lo posible por salvaguardar la informaci&oacute;n.</p>
                    <p>El usuario es responsable de mantener la confidencialidad del usuario y contrase&ntilde;a para el ingreso al portal electr&oacute;nico www.contiplus.net. El usuario es responsable de los usos relacionados con su usuario y contrase&ntilde;a a trav&eacute;s del portal electr&oacute;nico www.contiplus.net, incluso en los casos en que dichos usos no hayan sido por &eacute;l autorizados.&nbsp;</p>
                    <p><b>Cookies</b><br />
                        Las cookies son peque&ntilde;as piezas de informaci&oacute;n que son enviadas por el sitio web al navegador.</p>
                    <p>Se almacenan en el disco duro de los equipos y utilizan para determinar las preferencias de los usuarios que acceden al portal electr&oacute;nico (www.contiplus.net), as&iacute; como para rastrear determinados comportamientos o actividades.</p>
                    <p>Las cookies permiten reconocer a los usuarios, detectar el ancho de banda que han seleccionado, identificar la informaci&oacute;n m&aacute;s destacada, calcular el tama&ntilde;o de la audiencia y medir algunos par&aacute;metros de tr&aacute;fico.</p>
                    <p><b>Confidencialidad</b><br />
                        Cuando el usuario se encuentre en el sitio web (www.contiplus.net), compartir&aacute; su informaci&oacute;n, salvo que se especifique lo contrario.</p>
                    <p>CONTINENTAL, no tiene obligaci&oacute;n alguna de mantener confidencial cualquier otra informaci&oacute;n que el usuario proporcione por medio de boletines y pl&aacute;ticas en l&iacute;nea (chats), as&iacute; como a trav&eacute;s de las cookies.</p>
                    <p>S&oacute;lo se podr&aacute; difundir la informaci&oacute;n en casos especiales, como identificar, localizar o realizar acciones legales contra aquellas personas que infrinjan las condiciones de servicio del sitio web (www.contiplus.net), causen da&ntilde;os a, o interfieran en, los derechos de CONTINENTAL, sus propiedades, de otros usuarios del portal o de cualquier persona que pudiese resultar perjudicada por dichas acciones.</p>
                    <p>CONTINENTAL NO vender&aacute;, regalar&aacute;, facilitar&aacute; ni alquilar&aacute; informaci&oacute;n confidencial a terceros. Si el usuario no desea que sus datos sean compartidos, podr&aacute; prescindir de un servicio determinado o abstenerse de participar en algunas actividades.</p>
                    <p>CONTINENTAL NO compartir&aacute; informaci&oacute;n confidencial con terceras partes, salvo expresa autorizaci&oacute;n de sus suscriptores o cuando por medio de una orden judicial se requiera para cumplir con ciertas disposiciones procesales.</p>
                    <p><b>Modificaciones en las Pol&iacute;ticas de Privacidad</b><br />
                        CONTINENTAL se reserva el derecho de efectuar en cualquier momento, modificaciones en las presentes pol&iacute;ticas de privacidad y adaptarlas a novedades legislativas, jurisprudenciales, as&iacute; como a pr&aacute;cticas del mercado. Las modificaciones sustanciales de la Pol&iacute;tica de Privacidad ser&aacute;n comunicadas al Titular antes o a m&aacute;s tardar al momento de implementar la modificaci&oacute;n. Cuando la modificaci&oacute;n verse sobre la finalidad del tratamiento de la informaci&oacute;n, CONTINENTAL solicitar&aacute; una nueva autorizaci&oacute;n al Titular de la informaci&oacute;n. .<br />
                        <b>Vigencia</b><br />
                        La presente Pol&iacute;tica de Privacidad se encuentra vigente desde el [incluir fecha].</p>
                </div>
            </div>
        </div>
    </div>
    <?php
}
